project_id = "datzmkiygocblpbebikw"

[functions.create-pix-payment]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.create-card-payment]
verify_jwt = false

[functions.create-asaas-payment]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false
